display_errors = On
error_reporting = E_ALL
date.timezone = Europe/Paris
; En dev, les e-mails partent vers Mailpit
sendmail_path = "/usr/bin/msmtp -t --host=mailpit --port=1025 --from=jury@saint-arnoux.local"
